### ISSUE TITLE
docker-compose.yml kullanımı

### ISSUE THREAD

**Issue by omerucel** [Teknasyon-Teknoloji/docker#1]
Aşağıdaki gibi bir port kullanımı yerine:

``` yaml
  ports:
    - "8080:80"
    - "3306:3306"
```

Şu şekilde bir kullanım tercih edilirse:

``` yaml
  ports:
    - 80
    - 3306
```

Tüm projeler için ayrı ayrı port ayarlamaya gerek kalmıyor. **docker ps** komutu ile hangi container 80 portunu hangi port üzerinden veriyor görülebilir. Bu sayede docker-compose.yml.sample dosyası yerine projelerde direk docker-compose.yml dosyası eklenebilir. Tek sorun genelde bu port konusu oluyor, eğer projede birden çok kişi varsa.

Ayrıca mysql servisi harici olarak projeye bağlanabilir:

``` yaml
[PROJECT NAME]:
  image: [IMAGE NAME]
  links:
     - mysql

mysql:
  image: mysql
  ports:
    - 3306
  environment:
    MYSQL_DATABASE: "database"
    MYSQL_ROOT_PASSWORD: ""
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  volumes:
    - ./docker-files/my.cnf:/etc/mysql/conf.d/my.cnf
```

Bu sayede proje imajı yeniden build edilse bile, composer ile çalışan mysql servisinin dataları korunmuş oluyor. Veritabanı yeniden oluşturulmuyor.

Aynı şekilde gearmand, memcache servisleri de harici olarak bağlanabilir. Bu işlemler yapıldıktan sonra supervisor yerine direk **php-fpm -F && nginx -g "daemon off;"** üzerinden uygulama servisi çalıştırılabilir.

Diğer bir konu da container isimleri. https://docs.docker.com/compose/compose-file/#container-name ayarı epey kullanışlı çalışan container'a hızlıca erişmek için. Diğer türlü docker_project_name_1 gibi bir isim üzerinden erişmek uzun oluyor.

**Comment by fustundag** [comment]
ports fikri güzel. O şekilde değiştirebiliriz.

docker-compose.yml.sample dosyasını kullanmaya devam edelim, çünkü port harici başka projeye ve development ortamına özel şeyler eklebilir.

Mysql de ayıralım. O da iyi olacaktır. Ama diğer servisler için yine supervisor kullanmaya devam edelim. Çünkü projeye özel başka servis(ler) gelebilir. ( Örneğin bir servis elastic search kullanmak isteyebilir. )

İsim için de bu yapıya geçelim, daha kullanışlı olacaktır.

@omerucel gerekli değişiklikleri yapıp commit geçebilir misin?

**Comment by omerucel** [comment]
Elastic search için de resmi imaj mevcut aslında: https://hub.docker.com/_/elasticsearch/ docker-compose ile örnek bir kullanım: https://github.com/deviantony/docker-elk

Aynı proje üzerinde çalışılıyorsa, bu geliştirme ortamının herkes için aynı olması gerekiyor. Bir geliştirici ekstra ne tür bir ayara ihtiyaç duyulabilir? Tüm ilgili dosyalar docker imajı içinde olduğundan eşit şartlar mevcut olmalı diye düşünüyorum. Örneğin şunlar bana fazlalık gibi geliyor. Bunlar imaj içine atılabilir direk build aşamasında. Farklı projeler için de farklı Dockerfile dosyası oluşturmak yeterli. 

``` yaml
  environment:
    APPLICATION_ENV: development
  volumes:
    - ./config-files/pinfo.php:/pinfo.php
    - ./config-files/vhost.conf:/etc/nginx/conf.d/vhost.conf
    - ./config-files/www.conf:/etc/php-fpm.d/www.conf
    - ./config-files/php-development.ini:/etc/php.d/php-development.ini
```

Aşağıdaki şekilde hem dockerfile hem docker-compose.yml dosyası çok daha kullanışlı olur:

``` yaml
[PROJECT NAME]:
  container_name: [PROJECT-NAME]
  image: [IMAGE NAME]
  ports:
    - 80
  command: php-fpm -F && nginx -g "daemon off;"
  links:
    - mysql
    - gearmand
    - memcached
    - elasticsearch
  volumes:
    - ./../:/data/project
    - /root/.bash_history

memcached:
  image: memcached

gearmand:
  image: pataquets/gearmand

elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - 9200
    - 9300

mysql:
  image: mysql
  container_name: [PROJECT-NAME]_mysql
  ports:
    - 3306
  environment:
    MYSQL_DATABASE: "database"
    MYSQL_ROOT_PASSWORD: ""
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  volumes:
    - ./config-files/my.cnf:/etc/mysql/conf.d/my.cnf
```

Diğer konuları aktaracağım bugün. Bunları da tartışabiliriz. Ben olabildiğinde servisleri ayrıştırmaya çalışıyorum. Sadece nginx ve php-fpm'i ayrıştırmada başarılı olamadım nedense.
